### ISSUE TITLE
doesn't build on fresh copy of nightly 1.23

### ISSUE THREAD

**Issue by soapdog** [pikkr/pikkr#71]
Trying this out on a fresh copy of nightly 1.23 and it gives me error building.

```
error[E0432]: unresolved import `x86intrin::mm256_setr_epi8`
 --> /home/soapdog/.cargo/registry/src/github.com-1ecc6299db9ec823/pikkr-0.16.0/src/avx.rs:1:24
  |
1 | use x86intrin::{m256i, mm256_setr_epi8};
  |                        ^^^^^^^^^^^^^^^ no `mm256_setr_epi8` in the root. Did you mean to use `mm_setr_epi8`?

error[E0432]: unresolved import `x86intrin::mm256_cmpeq_epi8`
 --> /home/soapdog/.cargo/registry/src/github.com-1ecc6299db9ec823/pikkr-0.16.0/src/index_builder.rs:4:24
  |
4 | use x86intrin::{m256i, mm256_cmpeq_epi8, mm256_movemask_epi8, mm256_setr_epi8};
  |                        ^^^^^^^^^^^^^^^^ no `mm256_cmpeq_epi8` in the root. Did you mean to use `mm_cmpeq_epi8`?

error[E0432]: unresolved import `x86intrin::mm256_movemask_epi8`
 --> /home/soapdog/.cargo/registry/src/github.com-1ecc6299db9ec823/pikkr-0.16.0/src/index_builder.rs:4:42
  |
4 | use x86intrin::{m256i, mm256_cmpeq_epi8, mm256_movemask_epi8, mm256_setr_epi8};
  |                                          ^^^^^^^^^^^^^^^^^^^ no `mm256_movemask_epi8` in the root. Did you mean to use `mm_movemask_epi8`?

error[E0432]: unresolved import `x86intrin::mm256_setr_epi8`
 --> /home/soapdog/.cargo/registry/src/github.com-1ecc6299db9ec823/pikkr-0.16.0/src/index_builder.rs:4:63
  |
4 | use x86intrin::{m256i, mm256_cmpeq_epi8, mm256_movemask_epi8, mm256_setr_epi8};
  |                                                               ^^^^^^^^^^^^^^^ no `mm256_setr_epi8` in the root. Did you mean to use `mm_setr_epi8`?

error: aborting due to 4 previous errors

error: failed to compile `desafio-5-rust-pikkr v0.1.0 (file:///mnt/c/Users/soapdog/prog/osprogramadores/desafio-5-rust-pikkr)`, intermediate artifacts can be found at `/mnt/c/Users/soapdog/prog/osprogramadores/desafio-5-rust-pikkr/target`

Caused by:
  Could not compile `pikkr`.
```

This was on an empty project trying ```cargo install``` just with Pikkr in the toml file.

**Comment by ubnt-intrepid** [comment]
@soapdog If you would like to use AVX2 acceleation, you should tell the compiler to use them by using `RUSTFLAGS`:
```command
$ RUSTFLAGS="-C target-feature=+avx2" cargo build --features avx-accel --release
```

@kjmrknsn Rust official team currently provides the new crate [`stdsimd`](https://github.com/rust-lang-nursery/stdsimd) to support higher abstruction of SIMD operations.  IMO this crate is ready for replace (unofficial) `x86intrin`.  It will help to provide this crate including SIMD for stable users.

**Comment by kjmrknsn** [comment]
@ubnt-intrepid Thanks for your cooperation and information. I'll check the crate out later.

**Comment by kjmrknsn** [comment]
I'll close this issue because there seems to be no more questions.
